name: Update Visualizations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Optional: Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Generate visualizations
      run: |
        mkdir -p images
        python code/visualize.py
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add images/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update visualizations" && git push)
