name: Simple Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple test
        run: echo "Hello, GitHub Actions is working!"
